language: node_js
node_js:
  - "8"
brancher:
  only:
    - "dev"
    - "master"
install:
    - "npm install"
    - "npm install -g codecov"
env:  
  global:
    - CODECOV_TOKEN: "7b6d764f-e0db-4384-8bde-b02baac9ff8c"
script:
  - 'npm run cover'